### ISSUE TITLE
Stop using plugin system in favor of Yii modules

### ISSUE THREAD

**Issue by LouisGac** [SamMousa/ls3-question-objects-spec#15] opened 2016-04-29 12:31 UTC
continuing: https://github.com/SamMousa/ls3-question-objects-spec/issues/13

We're using Yii framework, a beautiful framework, used by dozen of thousands of coders over the world, written by extremely good coders, who spend their whole working time about framework questions since years. We're focusing on a survey system, they're focusing on questions such as : "how to handle an extension system".

So, they written an extension system, a very good one, handling any kind of problems an extension system can face, tested by a large community of application makers. It provides a way to build clean extensions, respecting standards such as MVC, thighly bound with Yii.

Instead of using this system, we're trying to use an "home made plugin system", full of problems, not respecting the most basic standards, not using the framework. So instead of focusing on our work problems like "how should we do mass actions", we quickly come to work on questions such as "how could we improve/correct/fix our home made plugin system".

That's a mistake. If we rather use the Yii Module system, any Yii coder on the world could write LimeSurvey modules. They could refer to the Yii documentation, instead of trying to understand the logic of our "home made solution".

**Comment by SamMousa** [comment] 2016-04-29 12:36
Duplicate of #13.

**Closed by SamMousa** 2016-04-29 12:36 UTC
